# Generated by Django 3.2.9 on 2021-11-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('continent', models.CharField(choices=[('ASIA', 'Asia'), ('SOUTH AMERICA', 'South America'), ('NORTH AMERICA', 'North America'), ('EUROPE', 'Europe'), ('AFRICA', 'Africa'), ('OCEANIA', 'Oceania'), ('ANTARCTICA', 'Antarctica')], max_length=20)),
                ('required', models.CharField(choices=[('DV', 'Double'), ('SV', 'Single'), ('No', 'No'), ('NA', 'Unknown')], max_length=20)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
